import { FullInitialState, Cliente, Servicio, Empleado, EquipoVehiculo, Conduce, PrecioCliente, ConfiguracionGasoil, CompraGasoil, DespachoGasoil, ConteoGasoil } from '../types/index.ts';

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id: 'cli-1',
    nombre: 'Constructora Mar Azul SRL',
    rnc: '1-31-45678-9',
    telefono: '(809) 555-0192',
    email: 'compras@marazul.com.do',
    direccion: 'Av. Winston Churchill #102, Piantini, Santo Domingo',
    contacto: 'Ing. Carlos Mendoza',
    estado: 'Activo',
    fechaCreacion: '2025-01-10',
  },
  {
    id: 'cli-2',
    nombre: 'Desarrollos Urbanos Bisonó',
    rnc: '1-01-98765-4',
    telefono: '(809) 555-0344',
    email: 'proyectos@bisono.com.do',
    direccion: 'Av. 27 de Febrero esq. Lincoln, Santo Domingo',
    contacto: 'Arq. Luisa Martínez',
    estado: 'Activo',
    fechaCreacion: '2025-01-15',
  },
  {
    id: 'cli-3',
    nombre: 'Grupo Ramos Obras & Infraestructura',
    rnc: '1-22-33445-1',
    telefono: '(809) 555-0811',
    email: 'obras@gruporamos.com.do',
    direccion: 'Av. Luperón km 6.5, Santo Domingo Oeste',
    contacto: 'Ing. Rafael Batista',
    estado: 'Activo',
    fechaCreacion: '2025-02-01',
  },
  {
    id: 'cli-4',
    nombre: 'Torres del Este SRL',
    rnc: '1-30-77889-2',
    telefono: '(829) 555-1234',
    email: 'contacto@torresdeleste.com',
    direccion: 'Boulevard Turístico del Este km 14, Punta Cana',
    contacto: 'Ing. Fernando Ortiz',
    estado: 'Activo',
    fechaCreacion: '2025-02-10',
  },
  {
    id: 'cli-5',
    nombre: 'Movimiento de Tierra del Caribe SRL',
    rnc: '1-02-65432-8',
    telefono: '(809) 555-4567',
    email: 'operaciones@mtcaribe.com.do',
    direccion: 'Autopista Duarte km 13, Los Alcarrizos',
    contacto: 'Ing. Pedro Almonte',
    estado: 'Activo',
    fechaCreacion: '2025-03-01',
  },
];

export const INITIAL_SERVICIOS: Servicio[] = [
  // Equipos pesados por hora
  {
    id: 'srv-1',
    codigo: 'EXC-320',
    descripcion: 'Alquiler Excavadora 320 (con operador)',
    unidadMedida: 'HORA',
    precioBase: 3200,
    categoria: 'Maquinaria Pesada',
    estado: 'Activo',
  },
  {
    id: 'srv-2',
    codigo: 'RETRO-01',
    descripcion: 'Alquiler Retroexcavadora / Pala (con operador)',
    unidadMedida: 'HORA',
    precioBase: 2400,
    categoria: 'Maquinaria Pesada',
    estado: 'Activo',
  },
  {
    id: 'srv-3',
    codigo: 'BULL-D6',
    descripcion: 'Alquiler Tractor / Buldócer D6 (con operador)',
    unidadMedida: 'HORA',
    precioBase: 3600,
    categoria: 'Maquinaria Pesada',
    estado: 'Activo',
  },
  {
    id: 'srv-4',
    codigo: 'ROD-COMP',
    descripcion: 'Alquiler Rodillo Compactador (con operador)',
    unidadMedida: 'HORA',
    precioBase: 2200,
    categoria: 'Maquinaria Pesada',
    estado: 'Activo',
  },
  // Materiales por m3
  {
    id: 'srv-5',
    codigo: 'MAT-GRAVA',
    descripcion: 'Grava 3/4"',
    unidadMedida: 'm3',
    precioBase: 950,
    categoria: 'Materiales / Mina',
    estado: 'Activo',
  },
  {
    id: 'srv-6',
    codigo: 'MAT-ARENA',
    descripcion: 'Arena Lavada',
    unidadMedida: 'm3',
    precioBase: 850,
    categoria: 'Materiales / Mina',
    estado: 'Activo',
  },
  {
    id: 'srv-7',
    codigo: 'MAT-RELLENO',
    descripcion: 'Material de Relleno (Tierra Común)',
    unidadMedida: 'm3',
    precioBase: 450,
    categoria: 'Materiales / Mina',
    estado: 'Activo',
  },
  {
    id: 'srv-8',
    codigo: 'MAT-GRANZOTE',
    descripcion: 'Granzote',
    unidadMedida: 'm3',
    precioBase: 700,
    categoria: 'Materiales / Mina',
    estado: 'Activo',
  },
  // Transporte por viaje
  {
    id: 'srv-9',
    codigo: 'TRAN-CORTO',
    descripcion: 'Flete de Volteo - Distancia Corta (<10km)',
    unidadMedida: 'VIAJE',
    precioBase: 2500,
    categoria: 'Transporte / Camiones',
    estado: 'Activo',
  },
  {
    id: 'srv-10',
    codigo: 'TRAN-LARGO',
    descripcion: 'Flete de Volteo - Distancia Larga (>10km)',
    unidadMedida: 'VIAJE',
    precioBase: 4200,
    categoria: 'Transporte / Camiones',
    estado: 'Activo',
  },
];

export const INITIAL_PRECIOS_CLIENTE: PrecioCliente[] = [
  {
    id: 'pc-1',
    clienteId: 'cli-1',
    clienteNombre: 'Constructora Mar Azul SRL',
    servicioId: 'srv-1',
    servicioDescripcion: 'Alquiler Excavadora 320 (con operador)',
    precioEspecial: 3000,
    notas: 'Tarifa corporativa Obra Torre Azul',
  },
  {
    id: 'pc-2',
    clienteId: 'cli-2',
    clienteNombre: 'Desarrollos Urbanos Bisonó',
    servicioId: 'srv-7',
    servicioDescripcion: 'Material de Relleno (Tierra Común)',
    precioEspecial: 420,
    notas: 'Contrato Anual Urbanización Las Praderas',
  },
];

export const INITIAL_EMPLEADOS: Empleado[] = [
  {
    id: 'emp-1',
    codigo: 'EMP-01',
    nombre: 'Juan Carlos Pérez',
    cedula: '001-1234567-8',
    telefono: '(829) 555-7801',
    cargo: 'Chofer de Camión',
    salarioBase: 22000,
    pagoPorViaje: 350,
    pagoPorMetro: 0,
    pagoPorHora: 0,
    estado: 'Activo',
  },
  {
    id: 'emp-2',
    codigo: 'EMP-02',
    nombre: 'Carlos Ramírez Méndez',
    cedula: '001-9876543-2',
    telefono: '(829) 555-7802',
    cargo: 'Chofer de Camión',
    salarioBase: 22000,
    pagoPorViaje: 350,
    pagoPorMetro: 0,
    pagoPorHora: 0,
    estado: 'Activo',
  },
  {
    id: 'emp-3',
    codigo: 'EMP-03',
    nombre: 'José Antonio Santana',
    cedula: '002-3456789-0',
    telefono: '(849) 555-7803',
    cargo: 'Operador de Maquinaria',
    salarioBase: 28000,
    pagoPorViaje: 0,
    pagoPorMetro: 0,
    pagoPorHora: 180,
    estado: 'Activo',
  },
  {
    id: 'emp-4',
    codigo: 'EMP-04',
    nombre: 'Manuel De Jesús Gómez',
    cedula: '001-5678901-3',
    telefono: '(809) 555-7804',
    cargo: 'Operador de Maquinaria',
    salarioBase: 28000,
    pagoPorViaje: 0,
    pagoPorMetro: 0,
    pagoPorHora: 180,
    estado: 'Activo',
  },
  {
    id: 'emp-5',
    codigo: 'EMP-05',
    nombre: 'Ramón Emilio Castillo',
    cedula: '047-0012345-6',
    telefono: '(809) 555-7805',
    cargo: 'Operador de Maquinaria',
    salarioBase: 28000,
    pagoPorViaje: 0,
    pagoPorMetro: 0,
    pagoPorHora: 180,
    estado: 'Activo',
  },
  {
    id: 'emp-6',
    codigo: 'EMP-06',
    nombre: 'Luis Alberto Fernández',
    cedula: '001-8765432-1',
    telefono: '(829) 555-7806',
    cargo: 'Mecánico',
    salarioBase: 35000,
    pagoPorViaje: 0,
    pagoPorMetro: 0,
    pagoPorHora: 0,
    estado: 'Activo',
  },
];

export const INITIAL_EQUIPOS: EquipoVehiculo[] = [
  {
    id: 'eq-1',
    codigo: 'EXC-01',
    ficha: 'Ficha #01 - Excavadora CAT 320',
    tipo: 'Retroexcavadora / Pala',
    marca: 'Caterpillar',
    modelo: '320 GC',
    placa: 'E-201145',
    ano: 2021,
    capacidadM3: 0,
    estado: 'Operativo',
    consumoPromedioGasoil: 12,
  },
  {
    id: 'eq-2',
    codigo: 'BULL-01',
    ficha: 'Ficha #02 - Buldócer Komatsu D65',
    tipo: 'Tractor / Buldócer',
    marca: 'Komatsu',
    modelo: 'D65PX',
    placa: 'E-198734',
    ano: 2020,
    capacidadM3: 0,
    estado: 'Operativo',
    consumoPromedioGasoil: 15,
  },
  {
    id: 'eq-3',
    codigo: 'ROD-01',
    ficha: 'Ficha #03 - Rodillo Compactador Dynapac',
    tipo: 'Rodillo Compactador',
    marca: 'Dynapac',
    modelo: 'CA2500D',
    placa: 'E-176220',
    ano: 2019,
    capacidadM3: 0,
    estado: 'Operativo',
    consumoPromedioGasoil: 8,
  },
  {
    id: 'eq-4',
    codigo: 'VOLT-01',
    ficha: 'Ficha #04 - Camión Volteo Freightliner',
    tipo: 'Camión Volteo',
    marca: 'Freightliner',
    modelo: '114SD',
    placa: 'L-389102',
    ano: 2021,
    capacidadM3: 12,
    estado: 'Operativo',
    consumoPromedioGasoil: 4.2,
  },
  {
    id: 'eq-5',
    codigo: 'VOLT-02',
    ficha: 'Ficha #05 - Camión Volteo Mack Granite',
    tipo: 'Camión Volteo',
    marca: 'Mack',
    modelo: 'Granite 8x4',
    placa: 'L-412093',
    ano: 2022,
    capacidadM3: 14,
    estado: 'Operativo',
    consumoPromedioGasoil: 4.0,
  },
  {
    id: 'eq-6',
    codigo: 'VOLT-03',
    ficha: 'Ficha #06 - Camión Volteo International',
    tipo: 'Camión Volteo',
    marca: 'International',
    modelo: 'WorkStar 7600',
    placa: 'L-376512',
    ano: 2020,
    capacidadM3: 12,
    estado: 'Mantenimiento',
    consumoPromedioGasoil: 4.5,
  },
];

export const INITIAL_CONDUCES: Conduce[] = [
  {
    id: 'cnd-1',
    numeroConduce: 'CON-2025-08101',
    tipoConduce: 'EQUIPO',
    fecha: '2025-08-15',
    hora: '07:30',
    clienteId: 'cli-1',
    clienteNombre: 'Constructora Mar Azul SRL',
    obra: 'Torre Vista Hermosa - Movimiento de Tierra Nivel 0',
    servicioId: 'srv-1',
    servicioDescripcion: 'Alquiler Excavadora 320 (con operador)',
    cantidad: 8,
    unidadMedida: 'HORA',
    precioUnitario: 3000,
    totalMonto: 24000,
    choferId: 'emp-3',
    choferNombre: 'José Antonio Santana',
    equipoId: 'eq-1',
    equipoFicha: 'Ficha #01 - Excavadora CAT 320',
    placa: 'E-201145',
    turnoHorario: 'Mañana',
    horaInicio: '07:00',
    horaFin: '15:00',
    horasTrabajadas: 8,
    rnc: '1-31-45678-9',
    sellado: true,
    estadoFacturacion: 'Facturado',
    numeroFactura: 'B0100004582',
    fechaFacturacion: '2025-08-16',
    comentarios: 'Excavación de zapatas, terreno normal.',
  },
  {
    id: 'cnd-2',
    numeroConduce: 'CON-2025-08102',
    tipoConduce: 'MATERIAL',
    fecha: '2025-08-15',
    hora: '08:45',
    clienteId: 'cli-2',
    clienteNombre: 'Desarrollos Urbanos Bisonó',
    obra: 'Residencial Alameda Real - Calle 3',
    servicioId: 'srv-7',
    servicioDescripcion: 'Material de Relleno (Tierra Común)',
    material: 'Material de Relleno (Tierra Común)',
    cantidad: 24,
    unidadMedida: 'm3',
    precioUnitario: 420,
    totalMonto: 10080,
    choferId: 'emp-1',
    choferNombre: 'Juan Carlos Pérez',
    equipoId: 'eq-4',
    equipoFicha: 'Ficha #04 - Camión Volteo Freightliner',
    placa: 'L-389102',
    viajes: 2,
    capacidadCamion: 12,
    sellado: true,
    estadoFacturacion: 'Pendiente',
    comentarios: 'Relleno compactado en capas de 20cm.',
  },
  {
    id: 'cnd-3',
    numeroConduce: 'CON-2025-08103',
    tipoConduce: 'EQUIPO',
    fecha: '2025-08-16',
    hora: '13:00',
    clienteId: 'cli-3',
    clienteNombre: 'Grupo Ramos Obras & Infraestructura',
    obra: 'Nave Logística Km 14 Autopista Duarte',
    servicioId: 'srv-3',
    servicioDescripcion: 'Alquiler Tractor / Buldócer D6 (con operador)',
    cantidad: 6,
    unidadMedida: 'HORA',
    precioUnitario: 3600,
    totalMonto: 21600,
    choferId: 'emp-4',
    choferNombre: 'Manuel De Jesús Gómez',
    equipoId: 'eq-2',
    equipoFicha: 'Ficha #02 - Buldócer Komatsu D65',
    placa: 'E-198734',
    turnoHorario: 'Tarde',
    horaInicio: '13:00',
    horaFin: '19:00',
    horasTrabajadas: 6,
    sellado: true,
    estadoFacturacion: 'Pendiente',
    comentarios: 'Nivelación de terreno para piso industrial.',
  },
  {
    id: 'cnd-4',
    numeroConduce: 'CON-2025-08104',
    tipoConduce: 'MATERIAL',
    fecha: '2025-08-17',
    hora: '10:00',
    clienteId: 'cli-4',
    clienteNombre: 'Torres del Este SRL',
    obra: 'Hotel Coral Bay - Zapatas Bloque C',
    servicioId: 'srv-5',
    servicioDescripcion: 'Grava 3/4"',
    material: 'Grava 3/4"',
    cantidad: 28,
    unidadMedida: 'm3',
    precioUnitario: 950,
    totalMonto: 26600,
    choferId: 'emp-2',
    choferNombre: 'Carlos Ramírez Méndez',
    equipoId: 'eq-5',
    equipoFicha: 'Ficha #05 - Camión Volteo Mack Granite',
    placa: 'L-412093',
    viajes: 2,
    capacidadCamion: 14,
    sellado: false,
    estadoFacturacion: 'Pendiente',
    comentarios: 'Descarga en zona de zapatas estructurales.',
  },
];

export const INITIAL_GASOIL_CONFIG: ConfiguracionGasoil = {
  capacidadTanquePrincipal: 3500,
  nivelActual: 2180,
  alertaNivelMinimo: 500,
  precioPorGalonDefecto: 242.5,
};

export const INITIAL_GASOIL_COMPRAS: CompraGasoil[] = [
  {
    id: 'gcom-1',
    fecha: '2025-08-01',
    proveedor: 'Distribuidora Dominicana de Combustibles (DICON)',
    numeroFactura: 'FAC-88902',
    galones: 1500,
    precioPorGalon: 240.0,
    total: 360000,
    recibidoPor: 'Luis Fernández (Mecánico)',
    notas: 'Descarga completa en tanque #1',
  },
  {
    id: 'gcom-2',
    fecha: '2025-08-12',
    proveedor: 'Distribuidora Dominicana de Combustibles (DICON)',
    numeroFactura: 'FAC-89310',
    galones: 1200,
    precioPorGalon: 242.5,
    total: 291000,
    recibidoPor: 'Luis Fernández (Mecánico)',
    notas: 'Suministro semanal de diésel',
  },
];

export const INITIAL_GASOIL_DESPACHOS: DespachoGasoil[] = [
  {
    id: 'gdes-1',
    fecha: '2025-08-15',
    hora: '06:30',
    equipoId: 'eq-1',
    equipoFicha: 'Ficha #01 - Excavadora CAT 320',
    empleadoId: 'emp-3',
    empleadoNombre: 'José Antonio Santana',
    galones: 55,
    horometroKm: 3410,
    conduceId: 'cnd-1',
    notas: 'Tanque lleno inicio de jornada',
  },
  {
    id: 'gdes-2',
    fecha: '2025-08-15',
    hora: '06:45',
    equipoId: 'eq-4',
    equipoFicha: 'Ficha #04 - Camión Volteo Freightliner',
    empleadoId: 'emp-1',
    empleadoNombre: 'Juan Carlos Pérez',
    galones: 45,
    horometroKm: 128450,
    conduceId: 'cnd-2',
    notas: 'Salida a Obra Alameda Real',
  },
  {
    id: 'gdes-3',
    fecha: '2025-08-17',
    hora: '07:15',
    equipoId: 'eq-2',
    equipoFicha: 'Ficha #02 - Buldócer Komatsu D65',
    empleadoId: 'emp-4',
    empleadoNombre: 'Manuel De Jesús Gómez',
    galones: 60,
    horometroKm: 890,
    notas: 'Nivelación nave logística',
  },
];

export const INITIAL_GASOIL_CONTEOS: ConteoGasoil[] = [
  {
    id: 'gcnt-1',
    fecha: '2025-08-10',
    hora: '18:00',
    galonesMedidos: 2450,
    galonesSistema: 2465,
    diferencia: -15,
    responsable: 'Ing. Supervisor de Patio',
    observacion: 'Calibración con varilla graduada tanque 1.',
  },
];

export async function seedDatabaseIfNeeded(): Promise<void> {
  const { DatabaseRepository } = await import('./repository.ts');
  const empty = await DatabaseRepository.isEmpty();
  if (!empty) {
    console.log('[EQUIPROCI Seed] La base de datos ya contiene datos; no se aplica el seed.');
    return;
  }
  console.log('[EQUIPROCI Seed] Base de datos vacía detectada. Insertando datos iniciales de ejemplo...');
  for (const c of INITIAL_CLIENTES) await DatabaseRepository.saveCliente(c);
  for (const s of INITIAL_SERVICIOS) await DatabaseRepository.saveServicio(s);
  for (const e of INITIAL_EMPLEADOS) await DatabaseRepository.saveEmpleado(e);
  for (const eq of INITIAL_EQUIPOS) await DatabaseRepository.saveEquipoVehiculo(eq);
  for (const p of INITIAL_PRECIOS_CLIENTE) await DatabaseRepository.savePrecioCliente(p);
  await DatabaseRepository.saveConfiguracionGasoil(INITIAL_GASOIL_CONFIG);
  for (const c of INITIAL_CONDUCES) await DatabaseRepository.saveConduce(c);
  for (const c of INITIAL_GASOIL_COMPRAS) await DatabaseRepository.saveCompraGasoil(c);
  for (const d of INITIAL_GASOIL_DESPACHOS) await DatabaseRepository.saveDespachoGasoil(d);
  for (const c of INITIAL_GASOIL_CONTEOS) await DatabaseRepository.saveConteoGasoil(c);
  // El nivel del tanque termina recalculado por las compras/despachos anteriores; se fija al valor de referencia inicial.
  await DatabaseRepository.saveConfiguracionGasoil({ nivelActual: INITIAL_GASOIL_CONFIG.nivelActual });
  console.log('[EQUIPROCI Seed] Datos iniciales insertados correctamente.');
}

export async function resetDatabaseToDefault(): Promise<void> {
  const { DatabaseRepository } = await import('./repository.ts');
  console.log('[EQUIPROCI Reset] Restableciendo base de datos a los valores por defecto...');
  await DatabaseRepository.truncateAll();
  await seedDatabaseIfNeeded();
}
